// Generated by build.py from parameters.json. Units: mm.
// Change parameters.json and rerun build.py to edit dimensions.
part = "assembly"; // [assembly,base,lid,fit-coupon,insert-coupon,print-layout]
module base() {
  difference() {
    union() {
      difference() {
        union() {
          translate([0, 0, 0]) linear_extrude(height=0.85, scale=1) offset(r=2.6, $fn=64) square([40, 36], center=true);
          translate([0, 0, 0.8]) linear_extrude(height=19.7, scale=1) offset(r=3, $fn=64) square([40, 36], center=true);
        }
        translate([0, 0, 2]) linear_extrude(height=20.5, scale=1) offset(r=1, $fn=64) square([40, 36], center=true);
      }
      translate([-13.3, -10, 1.95]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 3.55]);
      translate([-13.3, 10, 1.95]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 3.55]);
      translate([13.3, -10, 1.95]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 3.55]);
      translate([13.3, 10, 1.95]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 3.55]);
      translate([-13.5, -10, 1.95]) translate([-0.5, -1.5, 0]) cube([1, 3, 4.3]);
      translate([-13.5, 10, 1.95]) translate([-0.5, -1.5, 0]) cube([1, 3, 4.3]);
      translate([13.5, -10, 1.95]) translate([-0.5, -1.5, 0]) cube([1, 3, 4.3]);
      translate([13.5, 10, 1.95]) translate([-0.5, -1.5, 0]) cube([1, 3, 4.3]);
      translate([0, -16.45, 1.95]) translate([-3, -0.5, 0]) cube([6, 1, 4.3]);
    }
    translate([0, 20, 4]) translate([-8, -3, 0]) cube([16, 6, 10]);
    translate([-17.5, 0, -0.05]) cylinder(h=2.1, r1=1.1, r2=1.1, $fn=64);
    translate([-17.5, 0, -0.05]) cylinder(h=1.05, r1=2.1, r2=1.1, $fn=64);
    translate([17.5, 0, -0.05]) cylinder(h=2.1, r1=1.1, r2=1.1, $fn=64);
    translate([17.5, 0, -0.05]) cylinder(h=1.05, r1=2.1, r2=1.1, $fn=64);
    translate([-12, -13, -0.05]) linear_extrude(height=0.55, scale=1) offset(r=1, $fn=64) square([6, 6], center=true);
    translate([-12, 13, -0.05]) linear_extrude(height=0.55, scale=1) offset(r=1, $fn=64) square([6, 6], center=true);
    translate([12, -13, -0.05]) linear_extrude(height=0.55, scale=1) offset(r=1, $fn=64) square([6, 6], center=true);
    translate([12, 13, -0.05]) linear_extrude(height=0.55, scale=1) offset(r=1, $fn=64) square([6, 6], center=true);
  }
}
module lid() {
  difference() {
    union() {
      union() {
        translate([0, 0, 0]) linear_extrude(height=1.25, scale=1) offset(r=3, $fn=64) square([40, 36], center=true);
        translate([0, 0, 1.2]) linear_extrude(height=0.3, scale=0.986957) offset(r=3, $fn=64) square([40, 36], center=true);
      }
      difference() {
        translate([0, 0, -2]) linear_extrude(height=2.05, scale=1) offset(r=1.7, $fn=64) square([38, 34], center=true);
        translate([0, 0, -2.05]) linear_extrude(height=2.15, scale=1) offset(r=0.5, $fn=64) square([38, 34], center=true);
      }
      translate([-17.5, 0, -18.2]) cylinder(h=18.25, r1=3.2, r2=3.2, $fn=64);
      translate([17.5, 0, -18.2]) cylinder(h=18.25, r1=3.2, r2=3.2, $fn=64);
      translate([-13.3, -10, -13.2]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 13.25]);
      translate([-13.3, 10, -13.2]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 13.25]);
      translate([13.3, -10, -13.2]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 13.25]);
      translate([13.3, 10, -13.2]) translate([-1.2, -1.5, 0]) cube([2.4, 3, 13.25]);
    }
    translate([0, 0, -0.05]) translate([-7.05, -7.05, 0]) cube([14.1, 14.1, 1.6]);
    translate([-17.5, 0, -18.25]) cylinder(h=3.25, r1=1.7, r2=1.7, $fn=64);
    translate([-17.5, 0, -18.25]) cylinder(h=6.55, r1=1.2, r2=1.2, $fn=64);
    translate([17.5, 0, -18.25]) cylinder(h=3.25, r1=1.7, r2=1.7, $fn=64);
    translate([17.5, 0, -18.25]) cylinder(h=6.55, r1=1.2, r2=1.2, $fn=64);
  }
}
module fit_coupon() {
  difference() {
    translate([0, 0, 0]) linear_extrude(height=1.5, scale=1) offset(r=2, $fn=64) square([62, 22], center=true);
    translate([-21.5, 0, -0.05]) translate([-7, -7, 0]) cube([14, 14, 1.6]);
    translate([-21.5, -13, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 1.6]);
    translate([0, 0, -0.05]) translate([-7.05, -7.05, 0]) cube([14.1, 14.1, 1.6]);
    translate([-0.75, -13, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 1.6]);
    translate([0.75, -13, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 1.6]);
    translate([21.5, 0, -0.05]) translate([-7.1, -7.1, 0]) cube([14.2, 14.2, 1.6]);
    translate([20, -13, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 1.6]);
    translate([21.5, -13, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 1.6]);
    translate([23, -13, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 1.6]);
  }
}
module insert_coupon() {
  difference() {
    union() {
      translate([0, 0, 0]) linear_extrude(height=1.5, scale=1) offset(r=1.5, $fn=64) square([45, 7], center=true);
      translate([-18, 0, 0]) cylinder(h=8, r1=3.2, r2=3.2, $fn=64);
      translate([-6, 0, 0]) cylinder(h=8, r1=3.2, r2=3.2, $fn=64);
      translate([6, 0, 0]) cylinder(h=8, r1=3.2, r2=3.2, $fn=64);
      translate([18, 0, 0]) cylinder(h=8, r1=3.2, r2=3.2, $fn=64);
    }
    translate([-18, 0, 4.8]) cylinder(h=3.25, r1=1.6, r2=1.6, $fn=64);
    translate([-18, 0, 1.5]) cylinder(h=6.55, r1=1.2, r2=1.2, $fn=64);
    translate([-18, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([-6, 0, 4.8]) cylinder(h=3.25, r1=1.65, r2=1.65, $fn=64);
    translate([-6, 0, 1.5]) cylinder(h=6.55, r1=1.2, r2=1.2, $fn=64);
    translate([-6.75, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([-5.25, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([6, 0, 4.8]) cylinder(h=3.25, r1=1.7, r2=1.7, $fn=64);
    translate([6, 0, 1.5]) cylinder(h=6.55, r1=1.2, r2=1.2, $fn=64);
    translate([4.5, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([6, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([7.5, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([18, 0, 4.8]) cylinder(h=3.25, r1=1.75, r2=1.75, $fn=64);
    translate([18, 0, 1.5]) cylinder(h=6.55, r1=1.2, r2=1.2, $fn=64);
    translate([15.75, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([17.25, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([18.75, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
    translate([20.25, -5, -0.05]) translate([-0.4, -0.75, 0]) cube([0.8, 1.5, 8.1]);
  }
}

if (part == "base") base();
else if (part == "lid") translate([0,0,1.5]) rotate([180,0,0]) lid();
else if (part == "fit-coupon") fit_coupon();
else if (part == "insert-coupon") insert_coupon();
else if (part == "print-layout") {
    base();
    translate([52.0,0,1.5]) rotate([180,0,0]) lid();
} else {
    color("#b8bbc0") base();
    translate([0,0,20.5]) color("#c4c7cb") lid();
}
